//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormaGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidature
    {
        public int Personne_IdPersonne { get; set; }
        public int Session_IdSession { get; set; }
        public int EtatCanditature { get; set; }
    
        public virtual Personne Personne { get; set; }
        public virtual Session Session { get; set; }
    }
}
